import { Injectable } from '@angular/core';

@Injectable()
export class QueueListService {

  
  queueRecords = [
    {
    RecordID: 1,
    AuthCreationDate: "2016-10-09T17:21:52Z",
    MemberID: "0344991326",
    MemberName: "Leonid Coulston",
    AuthNumber: "4617668780",
    State: "TX",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "lcoulston0",
    Urgency: "policy",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 14,
    PendingColor: 4,
    FollowUpOne: [true,true,false],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 2,
    AuthCreationDate: "2017-04-16T17:12:35Z",
    MemberID: "3444558449",
    MemberName: "Willie Costar",
    AuthNumber: "3764073071",
    State: "TX",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "wcostar1",
    Urgency: "knowledge base",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 52,
    PendingColor: 1,
    FollowUpOne: [true,true,false],
    FollowUpTwo: false,
    FollowUpThree: false,
    IsLocked: true
  }, {
    RecordID: 3,
    AuthCreationDate: "2017-03-29T09:57:14Z",
    MemberID: "3960733941",
    MemberName: "Vittoria Meriton",
    AuthNumber: "0191606006",
    State: "TN",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "vmeriton2",
    Urgency: "grid-enabled",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 61,
    PendingColor: 2,
    FollowUpOne: [false,false,false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: true
  }, {
    RecordID: 4,
    AuthCreationDate: "2017-08-16T11:00:56Z",
    MemberID: "8847119138",
    MemberName: "Clemence Housegoe",
    AuthNumber: "8157656206",
    State: "DC",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "chousegoe3",
    Urgency: "3rd generation",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 28,
    PendingColor: 2,
    FollowUpOne: [true, true, true],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 5,
    AuthCreationDate: "2017-08-18T16:49:15Z",
    MemberID: "5079870494",
    MemberName: "Lindsey Madge",
    AuthNumber: "2136337645",
    State: "NV",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "lmadge4",
    Urgency: "frame",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 62,
    PendingColor: 3,
    FollowUpOne: [false, false, false],
    FollowUpTwo: false,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 6,
    AuthCreationDate: "2017-06-07T21:39:56Z",
    MemberID: "6424811559",
    MemberName: "Meggy Battyll",
    AuthNumber: "7339189378",
    State: "AL",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "mbattyll5",
    Urgency: "next generation",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 80,
    PendingColor: 3,
    FollowUpOne: [false, false, false],
    FollowUpTwo: false,
    FollowUpThree: false,
    IsLocked: true
  }, {
    RecordID: 7,
    AuthCreationDate: "2017-06-30T01:47:25Z",
    MemberID: "5696950779",
    MemberName: "Maximo Di Nisco",
    AuthNumber: "8234928929",
    State: "CA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "mdi6",
    Urgency: "contingency",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 89,
    PendingColor: 4,
    FollowUpOne: [false, false, false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 8,
    AuthCreationDate: "2017-01-01T19:45:33Z",
    MemberID: "2695537743",
    MemberName: "Gwenni Ochterlony",
    AuthNumber: "0476576296",
    State: "PA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "gochterlony7",
    Urgency: "system-worthy",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 15,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 9,
    AuthCreationDate: "2016-07-05T06:25:41Z",
    MemberID: "6985162770",
    MemberName: "Hansiain Ruseworth",
    AuthNumber: "1952190037",
    State: "TX",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "hruseworth8",
    Urgency: "Reduced",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 32,
    PendingColor: 1,
    FollowUpOne: [false, true, false],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 10,
    AuthCreationDate: "2017-03-06T09:02:09Z",
    MemberID: "9082288958",
    MemberName: "Giulia Pollicott",
    AuthNumber: "9015625875",
    State: "OR",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "gpollicott9",
    Urgency: "Front-line",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 14,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: true,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 11,
    AuthCreationDate: "2016-11-13T04:55:06Z",
    MemberID: "0444339191",
    MemberName: "Livvyy Crofthwaite",
    AuthNumber: "1858292069",
    State: "IL",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "lcrofthwaitea",
    Urgency: "Front-line",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 71,
    PendingColor: 1,
    FollowUpOne: [false, true, false],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 12,
    AuthCreationDate: "2017-01-10T07:11:38Z",
    MemberID: "9187496216",
    MemberName: "Price Astlatt",
    AuthNumber: "4077032369",
    State: "VA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "pastlattb",
    Urgency: "Grass-roots",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 9,
    PendingColor: 1,
    FollowUpOne: [true, true, false],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 13,
    AuthCreationDate: "2016-07-08T00:54:23Z",
    MemberID: "1848460619",
    MemberName: "Ax Forbes",
    AuthNumber: "4183855306",
    State: "MA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "aforbesc",
    Urgency: "heuristic",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 86,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 14,
    AuthCreationDate: "2016-07-23T23:33:01Z",
    MemberID: "2519830018",
    MemberName: "Juliann Thake",
    AuthNumber: "4202872444",
    State: "GA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "jthaked",
    Urgency: "asymmetric",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 74,
    PendingColor: 4,
    FollowUpOne: false,
    FollowUpTwo: true,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 15,
    AuthCreationDate: "2016-11-02T04:23:56Z",
    MemberID: "1452545561",
    MemberName: "Cynthia Ickovitz",
    AuthNumber: "6619561861",
    State: "MD",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "cickovitze",
    Urgency: "Visionary",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 22,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 16,
    AuthCreationDate: "2017-07-25T00:15:52Z",
    MemberID: "4540733729",
    MemberName: "Mikel Hendrichs",
    AuthNumber: "2328880517",
    State: "WA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "mhendrichsf",
    Urgency: "leverage",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 22,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: true,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 17,
    AuthCreationDate: "2016-09-02T10:06:20Z",
    MemberID: "9319105413",
    MemberName: "Shauna Exall",
    AuthNumber: "8358718187",
    State: "FL",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "sexallg",
    Urgency: "local",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 67,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: false,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 18,
    AuthCreationDate: "2016-08-03T08:00:15Z",
    MemberID: "9722871145",
    MemberName: "Brenden Tunsley",
    AuthNumber: "9622903991",
    State: "TX",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "btunsleyh",
    Urgency: "dynamic",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 46,
    FollowUpOne: [false, false, false],
    FollowUpTwo: true,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 19,
    AuthCreationDate: "2017-02-19T14:00:11Z",
    MemberID: "7980412486",
    MemberName: "Roderigo Becke",
    AuthNumber: "8318670302",
    State: "MA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "rbeckei",
    Urgency: "logistical",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 85,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 20,
    AuthCreationDate: "2017-07-05T01:21:26Z",
    MemberID: "6102764293",
    MemberName: "Tessa Plumstead",
    AuthNumber: "2227131446",
    State: "TX",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "tplumsteadj",
    Urgency: "extranet",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 16,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 21,
    AuthCreationDate: "2016-10-31T20:35:25Z",
    MemberID: "8183503616",
    MemberName: "Aaron Gard",
    AuthNumber: "4889144927",
    State: "PA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "agardk",
    Urgency: "Ameliorated",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 59,
    PendingColor: 1,
    FollowUpOne: [true, true, false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 22,
    AuthCreationDate: "2017-04-07T14:51:18Z",
    MemberID: "7365869348",
    MemberName: "Valle Gier",
    AuthNumber: "4284874268",
    State: "AL",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "vgierl",
    Urgency: "Customizable",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 48,
    PendingColor: 1,
    FollowUpOne: [true, true, false],
    FollowUpTwo: false,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 23,
    AuthCreationDate: "2016-12-05T23:55:37Z",
    MemberID: "5028376794",
    MemberName: "Savina Terzza",
    AuthNumber: "4758135592",
    State: "CA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "sterzzam",
    Urgency: "paradigm",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 3,
    PendingColor: 1,
    FollowUpOne: [true, true, false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 24,
    AuthCreationDate: "2016-11-14T19:42:16Z",
    MemberID: "7124582830",
    MemberName: "Jorge Ivain",
    AuthNumber: "0485428970",
    State: "NV",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "jivainn",
    Urgency: "benchmark",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 81,
    PendingColor: 1,
    FollowUpOne: [true, false, false],
    FollowUpTwo: true,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 25,
    AuthCreationDate: "2016-09-17T04:02:11Z",
    MemberID: "1064213073",
    MemberName: "Gian Addey",
    AuthNumber: "8091878818",
    State: "CA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "gaddeyo",
    Urgency: "internet solution",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 7,
    PendingColor: 1,
    FollowUpOne: [true, true, false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 26,
    AuthCreationDate: "2017-01-26T03:24:40Z",
    MemberID: "4610831813",
    MemberName: "Olimpia Bravington",
    AuthNumber: "1074639227",
    State: "VA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "obravingtonp",
    Urgency: "Fully-configurable",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 63,
    PendingColor: 1,
    FollowUpOne: [true, true, false],
    FollowUpTwo: false,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 27,
    AuthCreationDate: "2017-07-02T09:28:41Z",
    MemberID: "4052016815",
    MemberName: "Katharyn Taylo",
    AuthNumber: "5487531188",
    State: "TX",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "ktayloq",
    Urgency: "Self-enabling",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 59,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: false
  }, {
    RecordID: 28,
    AuthCreationDate: "2017-07-07T10:41:47Z",
    MemberID: "1286404878",
    MemberName: "Barny Scarasbrick",
    AuthNumber: "8463197523",
    State: "GA",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "bscarasbrickr",
    Urgency: "6th generation",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 70,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: true,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 29,
    AuthCreationDate: "2017-06-20T09:50:21Z",
    MemberID: "0068265654",
    MemberName: "Lucila Borthram",
    AuthNumber: "6991130869",
    State: "DC",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "lborthrams",
    Urgency: "monitoring",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 31,
    PendingColor: 1,
    FollowUpOne: [false, false, false],
    FollowUpTwo: true,
    FollowUpThree: false,
    IsLocked: false
  }, {
    RecordID: 30,
    AuthCreationDate: "2017-04-14T09:33:11Z",
    MemberID: "0348758979",
    MemberName: "Nicoline Nye",
    AuthNumber: "8688644101",
    State: "MI",
    DMEProvider: "Advanced Respiratory",
    HandledBy: "nnyet",
    Urgency: "moratorium",
    Queue: "TLR",
    AuthStatus: "Unsubmitted",
    TotalTime: 64,
    PendingColor: 1,
    FollowUpOne: [true, true, false],
    FollowUpTwo: false,
    FollowUpThree: true,
    IsLocked: false
  }]  
 
  states = [
    {label: 'DC', value: 'DC'},
    {label: 'GA', value: 'GA'},
    {label: 'TN', value: 'TN'}
  ];

  providers = [
    {label: 'Advanced Respiratory', value: 'Advanced Respiratory'},
    {label: 'American Home Paitent', value: 'American Home Patient'}    
  ];

  urgencies = [
    {label: 'Standard', value: 'Standard'},
    {label: 'Urgent', value: 'Urgent'}    
  ];

  queues = [
    {label: 'TLR', value: 'TLR'},
    {label: 'Repair FLR', value: 'Repair FLR'}    
  ];

  statuses = [
    {label: 'Unsubmitted', value: 'Unsubmitted'},
    {label: 'Canceled', value: 'Canceled'},
    {label: 'Submitted', value: 'Submitted'}
  ];
  
  constructor() { }

  getTableData(){
    return this.queueRecords;
  }

  getStates(){    
    return this.states;
  }

  getAuthStatuses(){
    return this.statuses;
  }

  getProviders(){
    return this.providers;
  }

  getUrgencies(){
    return this.urgencies;
  }

  getQueues(){
    return this.queues;
  }

}
